# Generated by Django 3.1.6 on 2021-03-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Content', models.TextField()),
                ('Author', models.CharField(max_length=25)),
                ('ts', models.DateTimeField(blank=True)),
            ],
        ),
    ]
