# Generated by Django 3.1.6 on 2021-03-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
