# Generated by Django 3.1.6 on 2021-03-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNo', models.CharField(max_length=13)),
                ('Issue', models.TextField()),
            ],
        ),
    ]
